# Generated by Django 4.1.1 on 2024-03-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='registration',
        ),
    ]
